on:
  pull_request:
    types:
      - closed
      
permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
          package-name: release-please-action
